// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    [Migration("20210120223812_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelAPI.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Date");

                    b.Property<int>("Rating");

                    b.Property<string>("Review")
                        .IsRequired();

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Orlando",
                            Country = "United States",
                            Date = "06/14/2019",
                            Rating = 3,
                            Review = "Disney world and Universal Studios all in one city, Whats not to like"
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "London",
                            Country = "United Kingdom",
                            Date = "10/28/2020",
                            Rating = 4,
                            Review = "Couldnt get the Royal Guards to laugh, but at least I didnt wind up in the tower of London"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Tokyo",
                            Country = "Japan",
                            Date = "04/14/2018",
                            Rating = 5,
                            Review = "The cherry blossom festival is a MUST SEE"
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Sydney",
                            Country = "Australia",
                            Date = "03/08/2019",
                            Rating = 4,
                            Review = "They wouldnt let me sing at the opera house, Must have been all the shrimp I ate off the barbie"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Toronto",
                            Country = "Canada",
                            Date = "12/11/2018",
                            Rating = 3,
                            Review = "Much to cold for my taste, But the Tim Hortens was fantastic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
